### ISSUE TITLE
无法给出返回结果，是讯飞接口问题？

### ISSUE THREAD

**Issue by gj0710** [Blushyes/BChat#3]
成功！2024-08-05 01:53:27,227 GLOBAL_LOG INFO: 问题：Q:马化腾是谁？
2024-08-05 01:53:27,227 GLOBAL_LOG INFO: 正在准备回复中......
2024-08-05 01:53:27,404 GLOBAL_LOG ERROR: 访问讯飞出错了
2024-08-05 01:53:27,404 GLOBAL_LOG ERROR: Error Code: 11200, Error: AppIdNoAuthError:(09:53:27.389) tokens.total
question 下面这句话如果和给定python列表中的任意一个字符串很相似，你就回答T，否则回答F，并告诉我跟哪个相似
例如：当列表为["你的职业是什么","yes"]，我给出的句子为"你的工作是？"的时候，因为"你的工作是？"和列表中的"你的职业是什么"是相似的，所以你要输出"T|你的职业是什么"
现在，列表为：['你是谁', '你是基于什么模型的', 'UP主是谁']，我给你的句子是："Q:马化腾是谁？"
Traceback (most recent call last):
  File "/app/main.py", line 10, in <module>
    start()
  File "/app/core/__init__.py", line 111, in start
    reply_self.start_loop()
  File "/app/core/__init__.py", line 27, in start_loop
    return asyncio.run(self._reply_loop())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/app/core/__init__.py", line 51, in _reply_loop
    if await reply(cmt):
  File "/app/core/__init__.py", line 76, in reply
    answer = xunfei.ask(cmt.message)
  File "/app/big_model/xunfei/__init__.py", line 55, in ask
    flag, answer = _pre_ask(content)
  File "/app/big_model/xunfei/__init__.py", line 81, in _pre_ask
    response = _proxy_ask(question)
  File "/app/big_model/xunfei/__init__.py", line 119, in _proxy_ask
    return _ask(content).generations[-1][-1].text
AttributeError: 'list' object has no attribute 'generations'

**Comment by Blushyes** [comment]
看起来确实是接口返回的内容不符合预期，可能是appid之类的没填对之类的导致星火返回了个错误提示的JSON？
可以看一下 `_ask(content)` 得到的返回值是啥样，当时写的仓促没弄错误处理。

**Comment by gj0710** [comment]
已解决，讯飞接口token问题
